global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "messagebus-app"
    static_configs:
      # Changed from host.docker.internal to the internal Docker service name
      - targets: ["app:9100"] 